# Generated by Django 4.2.7 on 2023-12-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.TextField(default='https://via.placeholder.com/800x400'),
        ),
        migrations.AddField(
            model_name='article',
            name='top_article',
            field=models.BooleanField(default=True),
        ),
    ]
