# Generated by Django 4.2.7 on 2023-12-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_image_article_top_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.TextField(default='general'),
        ),
        migrations.AlterField(
            model_name='article',
            name='top_article',
            field=models.BooleanField(default=False),
        ),
    ]
