# Generated by Django 4.2.7 on 2023-12-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_category_alter_article_top_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(default='none', verbose_name=100),
            preserve_default=False,
        ),
    ]
