# Generated by Django 4.2.7 on 2023-12-31 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.TextField(default='images/Rubik-Distressed-_1_.webp'),
        ),
    ]
