# Generated by Django 5.1.6 on 2025-02-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.TextField(default='images/apexblue/apexblue.webp'),
        ),
    ]
