# Generated by Django 4.2.6 on 2023-10-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('primary_muscle', models.CharField(max_length=100)),
                ('exercise_type', models.CharField(max_length=100)),
                ('other_names', models.TextField()),
                ('image_url', models.URLField()),
                ('video_url', models.URLField()),
                ('instructions', models.TextField()),
                ('equipment', models.CharField(max_length=255)),
            ],
        ),
    ]
