# Generated by Django 4.2.7 on 2023-11-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_alter_exercise_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='image_url',
            field=models.URLField(default='https://example.com/exercise_image.jpg'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='video_url',
            field=models.URLField(default='https://example.com/exercise_video.mp4'),
        ),
    ]
